[meta]
title = "Node Voice Agent Starter"
description = "Get started using Deepgram's Voice Agent with this Node demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "Agent"
language = "TypeScript"
framework = "Node"
sdk = "latest"

[build]
command = "npm install"

[config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `npm start` to start the server."
